//! Owns the T3 connection on a dedicated tokio thread.
//!
//! GPUI runs its own executor, so the UI talks to this thread through channels:
//! `Command`s in, `Event`s out. The backend handles pairing, credential storage
//! and reconnects; after a reconnect it resubscribes and the fresh snapshots
//! replace the UI state.

use std::path::PathBuf;
use std::time::Duration;

use futures::channel::mpsc as ui_channel;
use serde_json::Value;
use t3_client::reqwest;
use t3_client::{
    Connection, Credentials, PairingLink, RpcError, ShellStreamItem, ThreadShell, ThreadStreamItem,
};
use tokio::sync::mpsc;

const CLIENT_LABEL: &str = "T3 GPUI";
const MAX_BACKOFF: Duration = Duration::from_secs(30);

async fn refresh_providers(connection: &Connection) -> Result<Vec<t3_client::ServerProvider>, String> {
    let value = connection.rpc().call::<Value>("server.refreshProviders", serde_json::json!({ "refreshModels": false }))
        .await.map_err(|error| describe(&error))?;
    serde_json::from_value(value["providers"].clone()).map_err(|error| error.to_string())
}

pub enum Command {
    Pair(String),
    StartLocal(PathBuf),
    RefreshConfig,
    OpenAsset(t3_client::attachments::UploadedAttachment),
    SaveDrafts(crate::drafts::DraftStore),
    UploadAttachment {
        thread_id: String,
        request_id: u64,
        attachment: t3_client::attachments::LocalAttachment,
    },
    Workspace {
        request_id: u64,
        scope: crate::workspace::WorkspaceScope,
        request: t3_client::WorkspaceRequest,
    },
    OpenThread(String),
    CloseThread,
    LoadArchived(String),
    LoadUsage {
        request_id: u64,
        window: t3_client::UsageWindow,
    },
    LoadLimits { request_id: u64 },
    /// `server.getSettings`; answered with `Event::Settings`.
    LoadSettings,
    /// `server.updateSettings`; answered with `Event::SettingsSaved`.
    UpdateSettings {
        request_id: u64,
        patch: Value,
    },
    ThreadAction {
        thread_id: String,
        action: t3_client::ThreadAction,
    },
    SendMessage {
        thread: ThreadShell,
        text: String,
        attachments: Vec<t3_client::attachments::UploadedAttachment>,
    },
    Interrupt {
        thread_id: String,
        turn_id: Option<String>,
    },
    /// `project.create`. `id` is generated by the caller (`t3_client::new_id`)
    /// so the UI can address the project before its `project.upserted` shell
    /// event arrives.
    CreateProject {
        id: String,
        title: String,
        workspace_root: String,
    },
    /// Sends a draft thread's first message: `thread.create`, then
    /// `thread.turn.start`. Reports `NewThreadFinished` for the create and
    /// `SendFinished` for the message, both under the draft's ID, which
    /// becomes the thread's ID so `T3App` can open it once it streams in.
    StartThread {
        draft: crate::drafts::DraftThread,
        title: String,
        text: String,
        attachments: Vec<t3_client::attachments::UploadedAttachment>,
    },
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Status {
    NeedsPairing,
    Connecting(String),
    Connected(String),
    Reconnecting { server: String, reason: String },
}

pub enum Event {
    Status(Status),
    AssetUrl(Result<String, String>),
    EnvironmentKey {
        server: String,
        key: String,
    },
    EnvironmentId {
        server: String,
        id: String,
    },
    Terminal {
        scope: crate::workspace::WorkspaceScope,
        item: t3_client::WorkspaceTerminalEvent,
    },
    DraftsLoaded(crate::drafts::DraftStore),
    AttachmentUploaded {
        thread_id: String,
        local_id: String,
        request_id: u64,
        result: Result<t3_client::attachments::UploadedAttachment, String>,
    },
    WorkspaceResult {
        request_id: u64,
        scope: crate::workspace::WorkspaceScope,
        result: Result<t3_client::WorkspaceResponse, String>,
    },
    PairFinished(bool),
    NewThreadFinished {
        thread_id: String,
        success: bool,
    },
    Shell(ShellStreamItem),
    Thread {
        thread_id: String,
        item: ThreadStreamItem,
    },
    ThreadUnavailable(String),
    Error(String),
    Config(t3_client::ServerConfig),
    Providers(Vec<t3_client::ServerProvider>),
    /// The environment's settings, from a load or the config stream.
    Settings(t3_client::ServerSettings),
    SettingsSaved {
        request_id: u64,
        result: Result<t3_client::ServerSettings, String>,
    },
    LimitsFinished { request_id: u64, result: Result<(), String> },
    Archived {
        request_id: String,
        snapshot: Option<t3_client::ShellSnapshot>,
    },
    Usage {
        request_id: u64,
        result: Result<t3_client::UsageSummary, String>,
    },
    ThreadActionFinished {
        thread_id: String,
        action: t3_client::ThreadAction,
        success: bool,
    },
    SendFinished {
        thread_id: String,
        text: String,
        success: bool,
        attachment_ids: Vec<String>,
    },
}

pub struct Backend {
    commands: mpsc::UnboundedSender<Command>,
    draft_writer: Option<
        std::sync::mpsc::Sender<(crate::drafts::DraftStore, Option<std::sync::mpsc::Sender<()>>)>,
    >,
}

impl Backend {
    pub fn spawn() -> (Self, ui_channel::UnboundedReceiver<Event>) {
        let (commands, command_rx) = mpsc::unbounded_channel();
        let (events, event_rx) = ui_channel::unbounded();
        let (draft_writer, draft_rx) = std::sync::mpsc::channel::<(
            crate::drafts::DraftStore,
            Option<std::sync::mpsc::Sender<()>>,
        )>();
        let draft_events = events.clone();
        std::thread::Builder::new()
            .name("t3-draft-writer".into())
            .spawn(move || {
                while let Ok((store, completion)) = draft_rx.recv() {
                    if let Some(path) = crate::drafts::default_path() {
                        if let Err(error) = store.save(path) {
                            let _ = draft_events.unbounded_send(Event::Error(format!(
                                "Could not save drafts: {error}"
                            )));
                        }
                    }
                    if let Some(completion) = completion {
                        let _ = completion.send(());
                    }
                }
            })
            .expect("failed to start draft writer");
        std::thread::Builder::new()
            .name("t3-backend".into())
            .spawn(move || {
                tokio::runtime::Builder::new_multi_thread()
                    .enable_all()
                    .build()
                    .expect("failed to start tokio runtime")
                    .block_on(run(command_rx, Emitter(events)));
            })
            .expect("failed to spawn backend thread");
        (Self { commands, draft_writer: Some(draft_writer) }, event_rx)
    }

    #[cfg(test)]
    pub fn for_test() -> (Self, mpsc::UnboundedReceiver<Command>) {
        let (commands, receiver) = mpsc::unbounded_channel();
        (Self { commands, draft_writer: None }, receiver)
    }

    pub fn send(&self, command: Command) {
        if let Command::SaveDrafts(store) = command {
            if let Some(writer) = &self.draft_writer {
                let _ = writer.send((store, None));
            }
        } else {
            let _ = self.commands.send(command);
        }
    }

    pub fn flush_drafts(&self, store: crate::drafts::DraftStore) {
        if let Some(writer) = &self.draft_writer {
            let (completion, result) = std::sync::mpsc::channel();
            if writer.send((store, Some(completion))).is_ok() {
                let _ = result.recv_timeout(Duration::from_secs(3));
            }
        }
    }
}

#[derive(Clone)]
struct Emitter(ui_channel::UnboundedSender<Event>);

impl Emitter {
    fn emit(&self, event: Event) {
        let _ = self.0.unbounded_send(event);
    }

    fn error(&self, message: impl Into<String>) {
        self.emit(Event::Error(message.into()));
    }
}

/// Aborts the task (and so drops its subscription, interrupting it server-side).
struct TaskGuard(tokio::task::JoinHandle<()>);

impl Drop for TaskGuard {
    fn drop(&mut self) {
        self.0.abort();
    }
}

enum SessionEnd {
    Disconnected(String),
    Repair(String),
    Local(PathBuf),
    Quit,
}

async fn run(mut commands: mpsc::UnboundedReceiver<Command>, events: Emitter) {
    let http = reqwest::Client::builder()
        .connect_timeout(Duration::from_secs(10))
        .timeout(Duration::from_secs(20))
        .build()
        .expect("failed to create HTTP client");
    let store = crate::drafts::default_path().map(crate::drafts::DraftStore::load).transpose();
    match store {
        Ok(store) => events.emit(Event::DraftsLoaded(store.unwrap_or_default())),
        Err(error) => events.error(format!("Could not load saved drafts: {error}")),
    }
    let mut credentials = load_credentials().filter(|c| !c.is_expired());
    let mut open_thread: Option<String> = None;
    let mut pending_pair: Option<String> = None;
    let mut pending_local: Option<PathBuf> = None;
    let mut managed: Option<crate::managed_server::ManagedServer> = None;
    let mut managed_executable: Option<PathBuf> = None;
    let mut backoff = Duration::from_secs(1);

    loop {
        if let Some(executable) = pending_local.take() {
            if let Some(previous) = managed.take() {
                let _ = previous.shutdown().await;
                credentials = None;
            }
            match crate::managed_server::ManagedServer::start(executable.clone(), &http).await {
                Ok(server) => {
                    if let Some(previous) = managed.take() {
                        let _ = previous.shutdown().await;
                    }
                    credentials = Some(server.credentials().clone());
                    events.emit(Event::EnvironmentKey {
                        server: server.base_url().to_string(),
                        key: "managed-local".into(),
                    });
                    managed = Some(server);
                    managed_executable = Some(executable);
                    open_thread = None;
                    events.emit(Event::PairFinished(true));
                }
                Err(error) => {
                    events.error(format!("Local server failed: {error}"));
                    events.emit(Event::PairFinished(false));
                }
            }
        }
        if let Some(server) = &mut managed {
            match server.try_wait() {
                Ok(Some(status)) => {
                    events.error(format!("Local server exited ({status}). Restarting."));
                    managed = None;
                    credentials = None;
                    pending_local = managed_executable.clone();
                    tokio::time::sleep(backoff).await;
                    backoff = (backoff * 2).min(MAX_BACKOFF);
                    continue;
                }
                Ok(None) if server.credentials().is_expired() => {
                    if let Err(error) = server.reauthenticate(&http).await {
                        events.error(error);
                    } else {
                        credentials = Some(server.credentials().clone());
                    }
                }
                _ => {}
            }
        }
        if let Some(link) = pending_pair.take() {
            match pair(&http, &link).await {
                Ok(paired) => {
                    if let Some(previous) = managed.take() {
                        let _ = previous.shutdown().await;
                    }
                    managed_executable = None;
                    open_thread = None;
                    save_credentials(&paired);
                    credentials = Some(paired);
                    events.emit(Event::PairFinished(true));
                }
                Err(error) => {
                    events.error(format!("Pairing failed: {error}"));
                    events.emit(Event::PairFinished(false));
                }
            }
        }

        let Some(current) = credentials.clone() else {
            events.emit(Event::Status(Status::NeedsPairing));
            match wait_offline(&mut commands, &mut open_thread, None, &events).await {
                Offline::Pair(link) => pending_pair = Some(link),
                Offline::Local(path) => pending_local = Some(path),
                Offline::Quit => return,
                Offline::Elapsed => {}
            }
            continue;
        };

        let server = current.base_url.to_string();
        events.emit(Event::Status(Status::Connecting(server.clone())));
        let reason = match Connection::connect(&http, &current).await {
            Ok(connection) => {
                backoff = Duration::from_secs(1);
                if let Ok(config) = connection.server_config().await {
                    if let Some(environment) = &config.environment {
                        events.emit(Event::EnvironmentId {
                            server: server.clone(),
                            id: environment.environment_id.clone(),
                        });
                    }
                    events.emit(Event::Config(config));
                }
                if let Ok(settings) = connection.get_settings().await {
                    events.emit(Event::Settings(settings));
                }
                events.emit(Event::Status(Status::Connected(server.clone())));
                match run_session(
                    &connection,
                    &http,
                    &current.base_url,
                    &mut commands,
                    &events,
                    &mut open_thread,
                )
                .await
                {
                    SessionEnd::Disconnected(reason) => reason,
                    SessionEnd::Repair(link) => {
                        pending_pair = Some(link);
                        continue;
                    }
                    SessionEnd::Local(path) => {
                        pending_local = Some(path);
                        continue;
                    }
                    SessionEnd::Quit => return,
                }
            }
            Err(error) if error.is_unauthorized() => {
                if let Some(server) = &mut managed {
                    match server.reauthenticate(&http).await {
                        Ok(()) => {
                            credentials = Some(server.credentials().clone());
                            continue;
                        }
                        Err(error) => {
                            events.error(error);
                            managed = None;
                            managed_executable = None;
                        }
                    }
                }
                clear_credentials();
                credentials = None;
                events.error("The server rejected this client. Pair again.");
                continue;
            }
            Err(error) => error.to_string(),
        };

        events.emit(Event::Status(Status::Reconnecting { server, reason }));
        match wait_offline(&mut commands, &mut open_thread, Some(backoff), &events).await {
            Offline::Pair(link) => pending_pair = Some(link),
            Offline::Local(path) => pending_local = Some(path),
            Offline::Quit => return,
            Offline::Elapsed => {}
        }
        backoff = (backoff * 2).min(MAX_BACKOFF);
    }
}

enum Offline {
    Pair(String),
    Local(PathBuf),
    Quit,
    Elapsed,
}

/// Handles commands while there is no connection, until `timeout` (if any).
async fn wait_offline(
    commands: &mut mpsc::UnboundedReceiver<Command>,
    open_thread: &mut Option<String>,
    timeout: Option<Duration>,
    events: &Emitter,
) -> Offline {
    let sleep = async {
        match timeout {
            Some(timeout) => tokio::time::sleep(timeout).await,
            None => std::future::pending().await,
        }
    };
    tokio::pin!(sleep);
    loop {
        tokio::select! {
            () = &mut sleep => return Offline::Elapsed,
            command = commands.recv() => match command {
                None => return Offline::Quit,
                Some(Command::Pair(link)) => return Offline::Pair(link),
                Some(Command::StartLocal(path)) => return Offline::Local(path),
                Some(Command::RefreshConfig | Command::OpenAsset(_)) => events.error("Reconnect to access the server."),
                Some(Command::SaveDrafts(store)) => save_drafts(store, &events).await,
                Some(Command::UploadAttachment { thread_id, request_id, attachment }) => events.emit(Event::AttachmentUploaded { thread_id, local_id: attachment.id, request_id, result: Err("Reconnect to upload this attachment.".into()) }),
                Some(Command::Workspace { request_id, scope, .. }) => events.emit(Event::WorkspaceResult { request_id, scope, result: Err("Reconnect to use the workspace.".into()) }),
                Some(Command::OpenThread(thread_id)) => *open_thread = Some(thread_id),
                Some(Command::CloseThread) => *open_thread = None,
                Some(Command::LoadArchived(request_id)) => {
                    events.emit(Event::Archived { request_id, snapshot: None });
                    events.error("Reconnect before browsing archived threads.");
                }
                Some(Command::LoadUsage { request_id, .. }) => {
                    events.emit(Event::Usage { request_id, result: Err("Reconnect to see usage.".into()) });
                }
                Some(Command::LoadLimits { request_id }) => events.emit(Event::LimitsFinished { request_id, result: Err("Reconnect to see limits.".into()) }),
                Some(Command::LoadSettings) => {}
                Some(Command::UpdateSettings { request_id, .. }) => events.emit(Event::SettingsSaved { request_id, result: Err("Reconnect to change server settings.".into()) }),
                Some(Command::SendMessage { thread, text, attachments }) => {
                    events.error("Cannot send while disconnected. Your draft has been kept.");
                    events.emit(Event::SendFinished { thread_id: thread.id, text, success: false, attachment_ids: attachments.iter().map(|a| a.id.clone()).collect() });
                }
                Some(Command::ThreadAction { thread_id, action }) => {
                    events.error("Reconnect before changing this thread or project.");
                    events.emit(Event::ThreadActionFinished { thread_id, action, success: false });
                }
                Some(Command::StartThread { draft, text, attachments, .. }) => {
                    events.error("Cannot send while disconnected. Your draft has been kept.");
                    events.emit(Event::NewThreadFinished { thread_id: draft.id.clone(), success: false });
                    events.emit(Event::SendFinished { thread_id: draft.id, text, success: false, attachment_ids: attachments.iter().map(|a| a.id.clone()).collect() });
                }
                // These all need a live server; the UI keeps the relevant
                // affordances disabled while offline.
                Some(
                    Command::Interrupt { .. }
                    | Command::CreateProject { .. },
                ) => events.error("Reconnect before changing this thread or project."),
            },
        }
    }
}

async fn run_session(
    connection: &Connection,
    http: &reqwest::Client,
    base_url: &url::Url,
    commands: &mut mpsc::UnboundedReceiver<Command>,
    events: &Emitter,
    open_thread: &mut Option<String>,
) -> SessionEnd {
    let config_connection = connection.clone();
    let config_events = events.clone();
    let _config = TaskGuard(tokio::spawn(async move {
        let mut current = None;
        match config_connection.server_config().await {
            Ok(config) => { current = Some(config.clone()); config_events.emit(Event::Config(config)); },
            Err(error) => {
                config_events.error(format!("Model list unavailable: {}", describe(&error)))
            }
        }
        if let Ok(mut updates) = config_connection
            .rpc()
            .subscribe::<Value>("subscribeServerConfig", serde_json::json!({ "usageLimitSources": true }))
        {
            while let Some(Ok(value)) = updates.next().await {
                if let Some(settings) = settings_from_config_event(&value) {
                    config_events.emit(Event::Settings(settings));
                }
                if t3_client::quotas::apply_config_event(&mut current, value).unwrap_or(false)
                    && let Some(config) = &current {
                    config_events.emit(Event::Config(config.clone()));
                }
            }
        }
    }));
    let shell = forward_shell(connection.clone(), events.clone());
    tokio::pin!(shell);
    let mut operations = tokio::task::JoinSet::new();
    let mut terminals: std::collections::HashMap<(String, String), TaskGuard> =
        std::collections::HashMap::new();
    let mut _thread =
        open_thread.clone().map(|thread_id| spawn_thread(connection, thread_id, events));

    loop {
        tokio::select! {
            reason = connection.closed() => return SessionEnd::Disconnected(reason),
            reason = &mut shell => return SessionEnd::Disconnected(reason),
            Some(result) = operations.join_next(), if !operations.is_empty() => {
                if let Err(error) = result { events.error(format!("Backend request stopped: {error}")); }
            }
            command = commands.recv() => match command {
                None => return SessionEnd::Quit,
                Some(Command::Pair(link)) => return SessionEnd::Repair(link),
                Some(Command::StartLocal(path)) => return SessionEnd::Local(path),
                Some(Command::RefreshConfig) => {
                    let connection = connection.clone(); let events = events.clone();
                    operations.spawn(async move { match refresh_providers(&connection).await { Ok(providers) => events.emit(Event::Providers(providers)), Err(error) => events.error(error) } });
                }
                Some(Command::LoadLimits { request_id }) => {
                    let connection = connection.clone(); let events = events.clone();
                    operations.spawn(async move {
                        let result = refresh_providers(&connection).await.map(|providers| events.emit(Event::Providers(providers)));
                        events.emit(Event::LimitsFinished { request_id, result });
                    });
                }
                Some(Command::LoadSettings) => {
                    let connection = connection.clone(); let events = events.clone();
                    operations.spawn(async move {
                        match connection.get_settings().await {
                            Ok(settings) => events.emit(Event::Settings(settings)),
                            Err(error) => events.error(format!("Settings unavailable: {}", describe(&error))),
                        }
                    });
                }
                Some(Command::UpdateSettings { request_id, patch }) => {
                    let connection = connection.clone(); let events = events.clone();
                    operations.spawn(async move {
                        let result = connection.update_settings(patch).await.map_err(|error| describe(&error));
                        events.emit(Event::SettingsSaved { request_id, result });
                    });
                }
                Some(Command::OpenAsset(attachment)) => {
                    let connection = connection.clone(); let events = events.clone(); let base_url = base_url.clone();
                    operations.spawn(async move {
                        let result = connection.rpc().call::<Value>("assets.createUrl", serde_json::json!({ "resource": { "_tag": "attachment", "attachmentId": attachment.id, "fileName": attachment.name, "mimeType": attachment.mime_type } })).await;
                        let result = result.map_err(|error| describe(&error)).and_then(|value| {
                            let relative = value["relativeUrl"].as_str().ok_or_else(|| "Asset URL is missing".to_owned())?;
                            let url = base_url.join(relative).map_err(|e| e.to_string())?;
                            if url.origin() != base_url.origin() { return Err("Asset URL points outside this server".into()); }
                            Ok(url.to_string())
                        });
                        events.emit(Event::AssetUrl(result));
                    });
                }
                Some(Command::SaveDrafts(store)) => save_drafts(store, &events).await,
                Some(Command::UploadAttachment { thread_id, request_id, attachment }) => {
                    let connection = connection.clone(); let http = http.clone(); let base_url = base_url.clone(); let events = events.clone();
                    operations.spawn(async move {
                        let local_id = attachment.id.clone();
                        let result = t3_client::attachments::upload_attachment(&connection, &http, &base_url, &attachment).await.map_err(|e| e.to_string());
                        events.emit(Event::AttachmentUploaded { thread_id, local_id, request_id, result });
                    });
                }
                Some(Command::Workspace { request_id, scope, request }) => {
                    let connection = connection.clone(); let events = events.clone();
                    if let t3_client::WorkspaceRequest::OpenTerminal { thread_id, terminal_id, cwd } | t3_client::WorkspaceRequest::RestartTerminal { thread_id, terminal_id, cwd } = &request {
                        let key = (thread_id.clone(), terminal_id.clone()); let thread_id = thread_id.clone(); let terminal_id = terminal_id.clone(); let cwd = cwd.clone();
                        terminals.insert(key,TaskGuard(tokio::spawn(async move {
                            let result = request.execute(&connection).await.map_err(|e| describe(&e));
                            let success = result.is_ok();
                            events.emit(Event::WorkspaceResult { request_id, scope: scope.clone(), result });
                            if !success { return; }
                            match connection.subscribe_terminal(&thread_id,&terminal_id,Some(&cwd)) {
                                Ok(mut stream) => {
                                    let mut reason = "Terminal output stream ended. Restart to reconnect.".to_owned();
                                    while let Some(item) = stream.next().await {
                                        match item {
                                            Ok(item) => events.emit(Event::Terminal { scope:scope.clone(), item }),
                                            Err(error) => { reason = format!("Terminal output stream ended: {}", describe(&error)); break; }
                                        }
                                    }
                                    events.emit(Event::Terminal { scope, item: t3_client::WorkspaceTerminalEvent::Error { thread_id, terminal_id, message: reason } });
                                }
                                Err(error) => events.emit(Event::Terminal { scope, item: t3_client::WorkspaceTerminalEvent::Error { thread_id, terminal_id, message: describe(&error) } }),
                            }
                        })));
                    } else {
                        if let t3_client::WorkspaceRequest::CloseTerminal { thread_id, terminal_id } = &request {
                            if let Some(terminal_id) = terminal_id { terminals.remove(&(thread_id.clone(),terminal_id.clone())); }
                            else { terminals.retain(|(id,_),_| id != thread_id); }
                        }
                        operations.spawn(async move { let result = request.execute(&connection).await.map_err(|e| describe(&e)); events.emit(Event::WorkspaceResult { request_id, scope, result }); });
                    }
                }
                Some(Command::OpenThread(thread_id)) => {
                    terminals.clear();
                    *open_thread = Some(thread_id.clone());
                    // Replacing the guard interrupts the previous thread's stream.
                    _thread = Some(spawn_thread(connection, thread_id, events));
                }
                Some(Command::CloseThread) => {
                    terminals.clear();
                    *open_thread = None;
                    _thread = None;
                }
                Some(Command::LoadArchived(request_id)) => {
                    let connection = connection.clone();
                    let events = events.clone();
                    operations.spawn(async move {
                        let snapshot = match connection.archived_shell().await {
                            Ok(snapshot) => Some(snapshot),
                            Err(error) => {
                                events.error(format!("Archive unavailable: {}", describe(&error)));
                                None
                            }
                        };
                        events.emit(Event::Archived { request_id, snapshot });
                    });
                }
                Some(Command::LoadUsage { request_id, window }) => {
                    let connection = connection.clone();
                    let events = events.clone();
                    operations.spawn(async move {
                        let result = connection.usage_summary(&window).await.map_err(|error| describe(&error));
                        events.emit(Event::Usage { request_id, result });
                    });
                }
                Some(Command::ThreadAction { thread_id, action }) => {
                    let connection = connection.clone();
                    let events = events.clone();
                    operations.spawn(async move {
                        let result = connection.dispatch(action.command(&thread_id)).await;
                        let success = result.is_ok();
                        if let Err(error) = result {
                            events.error(format!("Thread update failed: {}", describe(&error)));
                        }
                        events.emit(Event::ThreadActionFinished { thread_id, action, success });
                    });
                }
                Some(Command::SendMessage { thread, text, attachments }) => {
                    let connection = connection.clone();
                    let events = events.clone();
                    operations.spawn(async move {
                        let result = connection.send_message_with_attachments(&thread, &text, &attachments).await;
                        let success = result.is_ok();
                        if let Err(error) = result {
                            events.error(format!("Send failed: {}", describe(&error)));
                        }
                        events.emit(Event::SendFinished { thread_id: thread.id, text, success, attachment_ids: attachments.iter().map(|a| a.id.clone()).collect() });
                    });
                }
                Some(Command::Interrupt { thread_id, turn_id }) => {
                    let connection = connection.clone();
                    let events = events.clone();
                    operations.spawn(async move {
                        if let Err(error) = connection.interrupt(&thread_id, turn_id.as_deref()).await {
                            events.error(format!("Stop failed: {}", describe(&error)));
                        }
                    });
                }
                Some(Command::CreateProject { id, title, workspace_root }) => {
                    let connection = connection.clone();
                    let events = events.clone();
                    operations.spawn(async move {
                        if let Err(error) = connection.create_project(&id, &title, &workspace_root).await
                        {
                            events.error(format!("Add project failed: {}", describe(&error)));
                        }
                    });
                }
                Some(Command::StartThread { draft, title, text, attachments }) => {
                    let connection = connection.clone();
                    let events = events.clone();
                    operations.spawn(async move {
                        let attachment_ids = attachments.iter().map(|a| a.id.clone()).collect();
                        let created = connection
                            .create_thread(&draft.id, &draft.project_id, &title, draft.model_selection.clone(), &draft.runtime_mode, &draft.interaction_mode)
                            .await;
                        if let Err(error) = created {
                            events.error(format!("New thread failed: {}", describe(&error)));
                            events.emit(Event::NewThreadFinished { thread_id: draft.id.clone(), success: false });
                            events.emit(Event::SendFinished { thread_id: draft.id, text, success: false, attachment_ids });
                            return;
                        }
                        events.emit(Event::NewThreadFinished { thread_id: draft.id.clone(), success: true });
                        let thread: ThreadShell = match serde_json::from_value(serde_json::json!({
                            "id": draft.id, "projectId": draft.project_id, "title": title,
                            "runtimeMode": draft.runtime_mode, "interactionMode": draft.interaction_mode,
                        })) {
                            Ok(thread) => thread,
                            Err(error) => {
                                events.error(format!("Send failed: {error}"));
                                events.emit(Event::SendFinished { thread_id: draft.id, text, success: false, attachment_ids });
                                return;
                            }
                        };
                        let result = connection.send_message_with_attachments(&thread, &text, &attachments).await;
                        let success = result.is_ok();
                        if let Err(error) = result {
                            events.error(format!("Send failed: {}", describe(&error)));
                        }
                        events.emit(Event::SendFinished { thread_id: thread.id, text, success, attachment_ids });
                    });
                }
            },
        }
    }
}

/// Settings carried by a `subscribeServerConfig` snapshot or `settingsUpdated`
/// event; other events carry none.
fn settings_from_config_event(event: &Value) -> Option<t3_client::ServerSettings> {
    let settings = match event["type"].as_str()? {
        "snapshot" => &event["config"]["settings"],
        "settingsUpdated" => &event["payload"]["settings"],
        _ => return None,
    };
    settings.is_object().then(|| t3_client::ServerSettings::from_value(settings.clone()))
}

async fn forward_shell(connection: Connection, events: Emitter) -> String {
    let mut stream = match connection.subscribe_shell() {
        Ok(stream) => stream,
        Err(error) => return format!("Shell subscription failed: {error}"),
    };
    while let Some(item) = stream.next().await {
        match item {
            Ok(item) => events.emit(Event::Shell(item)),
            Err(RpcError::Decode(error)) => eprintln!("skipping shell item: {error}"),
            Err(error) => return format!("Shell stream ended: {}", describe(&error)),
        }
    }
    "Shell stream ended".into()
}

fn spawn_thread(connection: &Connection, thread_id: String, events: &Emitter) -> TaskGuard {
    let connection = connection.clone();
    let events = events.clone();
    TaskGuard(tokio::spawn(async move {
        // No turn limit: load the thread's full history (see
        // `Connection::subscribe_thread`'s doc comment for what an absent
        // `turnLimit` means to the server).
        let mut stream = match connection.subscribe_thread(&thread_id, None) {
            Ok(stream) => stream,
            Err(error) => {
                events.error(format!("Thread subscription failed: {error}"));
                events.emit(Event::ThreadUnavailable(thread_id));
                return;
            }
        };
        while let Some(item) = stream.next().await {
            match item {
                Ok(item) => events.emit(Event::Thread { thread_id: thread_id.clone(), item }),
                Err(RpcError::Decode(error)) => eprintln!("skipping thread item: {error}"),
                Err(error) => {
                    events.error(format!("Thread stream ended: {}", describe(&error)));
                    events.emit(Event::ThreadUnavailable(thread_id));
                    return;
                }
            }
        }
        events.error("Thread stream ended. Select the thread again to retry.");
        events.emit(Event::ThreadUnavailable(thread_id));
    }))
}

async fn save_drafts(store: crate::drafts::DraftStore, events: &Emitter) {
    let Some(path) = crate::drafts::default_path() else {
        return;
    };
    match tokio::task::spawn_blocking(move || store.save(path)).await {
        Ok(Ok(())) => {}
        Ok(Err(error)) => events.error(format!("Could not save drafts: {error}")),
        Err(error) => events.error(format!("Draft save stopped: {error}")),
    }
}

async fn pair(http: &reqwest::Client, link: &str) -> Result<Credentials, t3_client::Error> {
    let link = PairingLink::parse(link)?;
    t3_client::auth::pair(http, &link, CLIENT_LABEL).await
}

/// Typed failures are tagged structs; show their tag and message if present.
fn describe(error: &RpcError) -> String {
    match error {
        RpcError::Failure(value) => {
            let tag = value.get("_tag").and_then(|v| v.as_str()).unwrap_or("Error");
            match value.get("message").and_then(|v| v.as_str()) {
                Some(message) => format!("{tag}: {message}"),
                None => format!("{tag}: {value}"),
            }
        }
        other => other.to_string(),
    }
}

fn credentials_path() -> Option<PathBuf> {
    Some(dirs::config_dir()?.join("t3-gpui").join("credentials.json"))
}

fn load_credentials() -> Option<Credentials> {
    let contents = std::fs::read_to_string(credentials_path()?).ok()?;
    serde_json::from_str(&contents).ok()
}

fn save_credentials(credentials: &Credentials) {
    let Some(path) = credentials_path() else {
        return;
    };
    let result = path.parent().map_or(Ok(()), std::fs::create_dir_all).and_then(|()| {
        let json = serde_json::to_string_pretty(credentials).map_err(std::io::Error::other)?;
        std::fs::write(&path, json)
    });
    if let Err(error) = result {
        eprintln!("could not save credentials to {}: {error}", path.display());
    }
}

fn clear_credentials() {
    if let Some(path) = credentials_path() {
        let _ = std::fs::remove_file(path);
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use futures::StreamExt as _;

    #[test]
    fn config_stream_settings_come_from_snapshots_and_settings_updates_only() {
        let updated = serde_json::json!({ "type": "settingsUpdated", "payload": { "settings": { "defaultRuntimeMode": "auto" } } });
        assert_eq!(settings_from_config_event(&updated).unwrap().default_runtime_mode(), "auto");
        let snapshot = serde_json::json!({ "type": "snapshot", "config": { "settings": { "defaultRuntimeMode": "auto" } } });
        assert!(settings_from_config_event(&snapshot).is_some());
        assert!(settings_from_config_event(&serde_json::json!({ "type": "snapshot", "config": {} })).is_none());
        assert!(settings_from_config_event(&serde_json::json!({ "type": "providerStatuses", "payload": {} })).is_none());
    }

    #[tokio::test]
    async fn offline_thread_creation_reports_failure_and_releases_waiter() {
        let (commands, mut receiver) = mpsc::unbounded_channel();
        let (events, mut output) = ui_channel::unbounded();
        commands
            .send(Command::StartThread {
                draft: crate::drafts::DraftThread {
                    id: "new-thread".into(),
                    project_id: "project".into(),
                    model_selection: serde_json::json!({}),
                    runtime_mode: "full-access".into(),
                    interaction_mode: "default".into(),
                },
                title: "Fix the build".into(),
                text: "Fix the build".into(),
                attachments: Vec::new(),
            })
            .unwrap();
        drop(commands);
        assert!(matches!(
            wait_offline(&mut receiver, &mut None, None, &Emitter(events)).await,
            Offline::Quit
        ));
        assert!(matches!(output.next().await, Some(Event::Error(_))));
        assert!(
            matches!(output.next().await, Some(Event::NewThreadFinished { thread_id, success: false }) if thread_id == "new-thread")
        );
        assert!(
            matches!(output.next().await, Some(Event::SendFinished { thread_id, success: false, .. }) if thread_id == "new-thread")
        );
    }

    #[tokio::test]
    async fn offline_send_returns_failure_so_composer_can_retry() {
        let (commands, mut command_rx) = mpsc::unbounded_channel();
        let (events, mut event_rx) = ui_channel::unbounded();
        let thread: ThreadShell = serde_json::from_value(serde_json::json!({
            "id": "thread-1", "projectId": "project-1", "title": "Test", "runtimeMode": "full-access"
        })).unwrap();
        commands
            .send(Command::SendMessage {
                thread,
                text: "Keep this draft".into(),
                attachments: vec![],
            })
            .unwrap();
        drop(commands);
        let mut open_thread = None;
        assert!(matches!(
            wait_offline(&mut command_rx, &mut open_thread, None, &Emitter(events)).await,
            Offline::Quit
        ));
        assert!(matches!(event_rx.next().await, Some(Event::Error(_))));
        assert!(
            matches!(event_rx.next().await, Some(Event::SendFinished { thread_id, text, success: false, .. }) if thread_id == "thread-1" && text == "Keep this draft")
        );
    }

    #[tokio::test]
    async fn offline_close_drops_the_thread_to_resubscribe() {
        let (commands, mut command_rx) = mpsc::unbounded_channel();
        let (events, _) = ui_channel::unbounded();
        commands.send(Command::CloseThread).unwrap();
        drop(commands);
        let mut open_thread = Some("archived-thread".into());
        wait_offline(&mut command_rx, &mut open_thread, None, &Emitter(events)).await;
        assert!(open_thread.is_none());
    }
}
